### ISSUE TITLE
many pdf problems

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#41]
In the archive smglom/sets all .zhs.tex fail for me, because font "FandolFang" cannot be found (and I don't know how to install it under Ubuntu).

many non-language .tex files end with `No pages of output.`

.tr.tex files have problems with `\endcsname`. 

The problems are best tested using run-pdflatex.sh (that is a link to run-latexml.sh) or i.e.:

```
maeder@lati:/var/data/localmh/MathHub/smglom/sets$ echo -e "log console\n log+ archive\n extension info.kwarc.mmt.stex.PdfLatex\n archive add .\n build smglom/sets pdflatex disjoint.tr.tex\n exit\n" | ../../../ext/MMT/mmt.jar
```

**Comment by kohlhase** [comment]
Jinbo knows what to do with the fonts.

**Comment by tkw1536** [comment]
@cmaeder see KWARC/localmh#217. You have to install the extra fonts. I already fixed this issue inside localmh_docker. 

I think you should really run MMT inside a docker container that has all dependencies set up (such as the provided by lmh), that way you don't have to keep worrying about dependencies

/cc @La-Stravaganza

**Comment by kohlhase** [comment]
I second that.

On 14/07/15 06:19, Tom Wiesing wrote:
>
> @cmaeder <https://github.com/cmaeder> see KWARC/localmh#217
> <https://github.com/KWARC/localmh/issues/217>. You have to install the
> extra fonts. I already fixed this issue inside localmh_docker.
>
> I think you should really run MMT inside a docker container that has
> all dependencies set up (such as the provided by lmh), that way you
> don't have to keep worrying about dependencies
>
> /cc @La-Stravaganza <https://github.com/La-Stravaganza>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/MMT/issues/41#issuecomment-121192773>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by cmaeder** [comment]
Since the fonts come from https://github.com/KWARC/sTeX/tree/master/fonts should not there be a installation procedure for them?

**Comment by tkw1536** [comment]
There is an installation procedure, it is performed inside the dockerfile
of localmh_docker and described in the issue I linked above.

**Comment by cmaeder** [comment]
After installing the fonts all .zhs.tex still fail (with non-zero exit status) although .pdf are created. A part of the output is:

```*(./bijective.zhs.aux) (/usr/share/texmf/tex/latex/tipa/t3cmr.fd)
ABD: EveryShipout initializing macros
*** you should *not* be loading the inputenc package
*** XeTeX expects the source to be in UTF8 encoding
*** some features of other encodings may conflict, resulting in poor output.

! LaTeX Error: Command `\tilde' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
<*> \begin{document}\begin
                          {modnl}[creators=Tianlin]{bijective}{zhs}
```

**Comment by cmaeder** [comment]
Meanwhile I ignore the exit code and only check for a non-empty pdf-file. Yet, the LaTeX errors may be investigated by someone else.

Calling mmt can be simplified by using " ; " (I only recently discovered the necessary spaces before and after ";")

```
maeder@lati:/var/data/localmh/MathHub/smglom/sets$ ../../../ext/MMT/mmt.jar "log console ; log+ archive ; extension info.kwarc.mmt.stex.PdfLatex ; archive add . ; build smglom/sets pdflatex disjoint.tr.tex ; exit"
```
